version: "3.7"
volumes:
  db-store:
  php-fpm-socket:
services:
  app:
    build: ./docker/php
    container_name: "hanly-app"
    volumes:
      - php-fpm-socket:/var/run/php-fpm:delegated
      - ../src:/work/backend:delegated
      - ./docker/php/bash/.bash_history:/root/.bash_history:delegated
      - ./docker/php/bash/psysh:/root/.config/psysh:delegated

  web:
    build: ./docker/nginx
    container_name: "hanly-web"
    ports:
      - 8080:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm:delegated
      - ../src:/work/backend:delegated

  db:
    build: ./docker/mysql
    container_name: "hanly-db"
    volumes:
      - db-store:/var/lib/mysql:delegated
    ports:
      - 33306:3306
